name: hackernews-daily-top

on:
  workflow_dispatch:
  schedule:
  - cron: "1 0 * * 1"

jobs:
  fetch-top-posts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: npm install
      run: npm install --only=prod
      working-directory: .
    - name: fetch
      run: node index.js
      working-directory: .
      # for github app auth
      env:
        GITHUB_TOKEN_VITALETS: ${{ secrets.GITHUB_TOKEN }}
        privateKey: ${{ secrets.privateKey }}
        
